version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backendContainer
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=postgresql://user:password@db:5432/library
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontendContainer
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
